protected/controllers/SiteController.php
<?php

class SiteController extends Controller {

    public $baseTitle = "Ing. Angelo Errico";

    /**
     * Declares class-based actions.
     */
    public function actions() {
        return array(
            // captcha action renders the CAPTCHA image displayed on the contact page
            'captcha' => array(
                'class' => 'CCaptchaAction',
                'backColor' => 0xFFFFFF,
            ),
            // page action renders "static" pages stored under 'protected/views/site/pages'
            // They can be accessed via: index.php?r=site/page&view=FileName
            'page' => array(
                'class' => 'CViewAction',
            ),
        );
    }

    /**
     * This is the default 'index' action that is invoked
     * when an action is not explicitly requested by users.
     */
    public function actionIndex() {
        $this->pageTitle = $this->baseTitle . ' - Homepage';
        $this->render('index');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError() {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact() {
        $this->pageTitle = $this->baseTitle . ' - Contatti';
        $this->layout = "main_page";
        $this->render('contact', array());
    }

    public function actionCostruzioni_edili() {
        $this->pageTitle = $this->baseTitle . ' - Costruzioni Edili';
        $this->layout = "main_page";
        $this->render('costruzioniedili', array());
    }

    public function actionRistrutturazioni() {
        $this->pageTitle = $this->baseTitle . ' - Ristrutturazioni';
        $this->layout = "main_page";
        $this->render('ristrutturazioni', array());
    }

    public function actionConsulenze_tecniche() {
        $this->pageTitle = $this->baseTitle . ' - Consulenze tecniche';
        $this->layout = "main_page";
        $this->render('consulenzetecniche', array());
    }

    public function actionStudio_tecnico() {
        $this->pageTitle = $this->baseTitle . ' - Studio tecnico';
        $this->layout = "main_page";
        $this->render('studiotecnico', array());
    }

    public function actionCalcoli_strutturali() {
        $this->pageTitle = $this->baseTitle . ' - Calcoli strutturali';
        $this->layout = "main_page";
        $this->render('calcolistrutturali', array());
    }

    public function actionCatasto() {
        $this->pageTitle = $this->baseTitle . ' - Catasto';
        $this->layout = "main_page";
        $this->render('catasto', array());
    }

    public function actionImmobili() {
        $this->pageTitle = $this->baseTitle . ' - Immobili';
        $this->layout = "main_page";
        $criteria = new CDbCriteria();
        $criteria->order = "posizione ASC";
        $criteria->condition = "eliminato = 0";
        $localitas = Localita::model()->findAll($criteria);

        $this->render('immobili', array(
            'localitas' => $localitas
        ));
    }

    public function actionMail() {
        
    }

    public function actionImmobile($id) {
                $this->pageTitle = $this->baseTitle . ' - Immobili';
        $this->layout = "main_page";
        $model = Immobile::model()->findByPk($id);
        if (!isset($model) || $model->pubblicato == 0 || $model->eliminato == 1) {
            $this->redirect($this->createUrl('/immobili'));
        }
        $this->render('immobile', array('model' => $model));
    }

}

protected/views/site/_header.php
<header id="header">
    <div class="container">
        <div class="row info-bar">
            <div class="col-sm-6">Tel. 0974 824945 - Cel. 335 8725255</div>
            <div class="col-sm-6 text-right">
                <a href="#" class="social-icon"><i class="icon fa fa-facebook"></i></a>
                <a href="#" class="social-icon"><i class="icon fa fa-youtube"></i></a>
            </div>
        </div>
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                <i class="icon fa fa-bars"></i>
            </button>
            <a class="navbar-brand normal" href="#home"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/logo.png" alt="uniform"/></a>
        </div>
        <nav class="collapse navbar-collapse navbar-right navbar-main-collapse">
            <ul id="nav" class="nav navbar-nav navigation">
                <li class="page-scroll menu-item"><a href="#home-slider">Home</a></li>
                <li class="page-scroll menu-item"><a href="#services">SERVIZI</a></li>
                <li class="page-scroll menu-item"><a href="<?php echo $this->createUrl('/immobili') ?>">IMMOBILI</a></li>
<!--                <li class="page-scroll menu-item"><a href="#projects">PROGETTI</a></li>-->
                <li class="page-scroll menu-item"><a href="#team">TEAM</a></li>
                <li class="page-scroll menu-item"><a href="#company">AZIENDA</a></li>
                <li class="page-scroll menu-item"><a href="#contact">CONTATTI</a></li>
            </ul>
        </nav>
    </div>
</header> 

protected/views/site/_map.php
<section id="map-section" class="section full-width">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 nopadding">
                <div id="map-container" class="map-wrapper"></div>
            </div>
        </div>
    </div>
</section>

protected/views/site/_portfolio.php
<!-- PORTFOLIO -->
<section class="section dark" id="projects">
    <div class="container">
        <div class="row">
            <div class="jt_col col-md-8 jt_col col-md-offset-2 text-center">
                <h2 class="title main">I Nostri Progetti</h2>
            </div>
        </div>
    </div>
</section>
<section class="section dark full-width" id="works">
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <ul class="filter">
                    <li class="filter-item"><a data-filter="*" class="active filter-link" href="#">Tutti</a></li>
                    <li class="filter-item"><a data-filter=".architecture" class="filter-link" href="#">Architettura</a></li>
                    <li class="filter-item"><a data-filter=".interior" class="filter-link" href="#">Appartamenti</a></li>
                    <li class="filter-item"><a data-filter=".construction" class="filter-link" href="#">Esterni</a></li>
                </ul>
                <div class="folio-grid clearfix voffset100">
                    <?php
                    $categories = array('architecture' => 'architecture', 'interior' => 'interior', 'construction' => 'construction');
                    for ($i = 1; $i < 10; $i++):
                        ?>
                        <article class="folio-item <?php echo array_rand($categories) ?> col-sm-4">
                            <a href="<?php echo $this->createUrl("/site/work", array('id' => $i)); ?>" class="folio-link">
                                <img src="http://placehold.it/853x568" class="img-responsive" alt=""/>
                                <div class="folio-over">
                                    <div class="folio-inner">
                                        <div class="folio-data">
                                            <h4 class="folio-name">uniform Vinyl House</h4>
                                            <h5 class="folio-type">Personal, Photography</h5>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </article>
                    <?php endfor; ?>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END PORTFOLIO -->

protected/views/site/_services.php
<!-- Services -->
<section id="services" class="section">
    <div class="container">
        <div class="row">
            <div class="jt_col col-md-8 jt_col col-md-offset-2 text-center">
                <h2 class="title main">COSA FACCIAMO</h2>
            </div>
        </div>
        <div class="row voffset100">
            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/costruzioni-edili'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_1.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Costruzioni edili</h3>
                        <a href="<?php echo $this->createUrl('/costruzioni-edili'); ?>" class="wwd-link">Leggi altro...</a>
                    </div>
                </div>
            </div>

            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/ristrutturazioni'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_2.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Ristrutturazioni</h3>
                        <a href="<?php echo $this->createUrl('/ristrutturazioni'); ?>" class="wwd-link">Leggi altro..</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/consulenze-tecniche'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_3.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Consulenze Tecniche</h3>
                        <a href="<?php echo $this->createUrl('/consulenze-tecniche'); ?>" class="wwd-link">Leggi altro..</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/studio-tecnico'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_4.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Studio Tecnico<br></h3>
                        <a href="<?php echo $this->createUrl('/studio-tecnico'); ?>" class="wwd-link">Leggi altro..</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/calcoli-strutturali'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_5.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Calcoli Strutturali</h3>
                        <a href="<?php echo $this->createUrl('/calcoli-strutturali'); ?>" class="wwd-link">Leggi altro..</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="wwd-block">
                    <a href="<?php echo $this->createUrl('/catasto'); ?>"><img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/cf_6.jpg" alt=""></a>
                    <div class="wwd-data">
                        <h3 class="wwd-title">Catasto</h3>
                        <a href="<?php echo $this->createUrl('/catasto'); ?>" class="wwd-link">Leggi altro..</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END Services -->

protected/views/site/contact.php
<!-- CONTACT -->
<section class="section" id="contact">
    <div class="container">
        <div class="row">
            <div class="jt_col-col-md-12 text-center voffset100">
                <h3 class="title main voffset100">CONTATTI</h3>
                <h3 class="title fz20 voffset0">VUOI UNA CONSULENZA?</h3>
                <h3 class="title primary fz50">+39 0974 824945</h3>
            </div>
            <div class="jt_col-col-md-12 voffset100">
                <form id="contactform" action="<?php echo $this->createUrl('/site/mail') ?>" method="post">
                    <div class="row text-center contact-form">
                        <div class="jt_col col-md-4">
                            <input id="name" name="name" type="text" class="required form-control" placeholder="Nome">
                        </div>
                        <div class="jt_col col-md-4">
                            <input id="email" name="email" type="text" class="required form-control" placeholder="Email">
                        </div>
                        <div class="jt_col col-md-4">
                            <input id="phone" name="phone" type="text" class="form-control" placeholder="Telefono">
                        </div>
                        <div class="jt_col col-md-12">
                            <textarea id="message" name="message" class="required form-control" placeholder="Messaggio"></textarea>
                        </div>
                        <div class="jt_col col-md-4 col-md-offset-4"><button type="submit" class="button fill">INVIA</button></div>
                        <div class="jt_col col-md-4 col-md-offset-4">
                            <div class="formSent success"><strong>Messaggio inviato con successo.</strong> Grazie per averci contattato!</div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="jt_col-col-md-12 voffset100 text-center">
                <h4 class="title fz16">ING. ANGELO ERRICO</h4>
                <h4 class="title fz16">via Difesa 6, Agropoli (SA)</h4>
                <h4 class="title fz16">TEL\FAX 0974 824945 | P.IVA 48789562</h4>
                <h4 class="title fz16 primary voffset60">APPALTITEMAIMPIANTI@LIBERO.IT</h4>
            </div>
        </div>
    </div>
</section>
<!-- END CONTACT -->

protected/views/site/immobili.php
<section class="section" id="basic">
    <div class="container" style="margin-bottom:30px;">
        <div class="row">
            <div class="jt_col col-md-8 jt_col col-md-offset-2 text-center">
                <h2 class="title main">IMMOBILI</h2>
            </div>
        </div>
        <div class="row">
            <div class="jt_col col-md-10 col-md-offset-1 text-center">
                <?php foreach ($localitas as $key => $localita): 
                    if($key != 0){
                        echo "&shy; - &shy;";
                    }
                    ?>
                    <a href="#sezione<?php echo $localita->id ?>" class="wwd-menuimm"><?php echo $localita->nome ?></a> 
                <?php endforeach; ?>
            </div>
        </div>
    </div>
</section>
<!-- IMMAGINE ESEMPIO-->
<div class="container">
    <div class="row">
        <div class="col-sm-10 col-sm-offset-1 post-image">
            <div class="generic-carousel" data-animation-out="slideOutRight" data-animation-in="slideInLeft" data-dots="false">
                <div class="item">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/immobili.png" alt="" class="img-responsive">
                </div>
                <div class="item">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/immobili.png" alt="" class="img-responsive">
                </div>
            </div>
        </div>
    </div>
</div>
<!-- FINE IMMAGINE ESEMPIO-->

<?php foreach ($localitas as $localita): ?>
    <!--SEZIONE LOCALITA -->
    <div class="container">
        <section id="sezione<?php echo $localita->id ?>"></section>
        <div class="row">
            <div class="jt_col col-md-8 jt_col col-md-offset-2 text-center">
                <h2 class="title main"><?php echo $localita->nome ?></h2>
            </div>
        </div>
        <div class="row voffset100">
            <?php
            $immobili = $localita->getImmobili();
            $class = "col-sm-4";
            if (count($immobili) == 1) {
                $class = "col-sm-4 col-sm-offset-4";
            } else if (count($immobili) == 2) {
                $class = "col-sm-4 col-sm-offset-1";
            }
            foreach ($immobili as $model):
                ?>
                <div class="<?php echo $class ?>">
                    <div class="wwd-block">
                        <a href="<?php echo $this->createUrl('/site/immobile', array('id' => $model->id)) ?>">
                            <div class="immobile-item-list" style="background-image: url('<?php echo $model->getCover() ?>')"></div>                            
                        </a>
                        <div class="wwd-data">
                            <h3 class="wwd-title"><?php echo $model->indirizzo ?></h3>
                            <h2 class="wwd-appart"><?php echo $model->tipologia ?></h2>
                            <a href="<?php echo $this->createUrl('/site/immobile', array('id' => $model->id)) ?>" class="wwd-link">DETTAGLI</a>
                        </div>
                    </div>
                </div>
    <?php endforeach; ?>
        </div>
    </div>
    <!--FINE SEZIONE LOCALITA-->
<?php endforeach; ?>

protected/views/site/index.php
<section id="home-slider">
    <div id="owl-main" class="owl-carousel">
        <div class="item">
            <div class="overlay"></div>
        </div>
        <div class="item">
            <div class="overlay"></div>
        </div>
        <div class="item">
            <div class="overlay"></div>
        </div>
    </div>
    <div class="slide-content">
        <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/slide-logo.png" alt="" class="slide-logo">
        <h3 class="slide-title">La nostra esperienza, al tuo servizio.</h3>
        <div id="owl-text" class="container" style="padding-bottom: 30px">
            <div class="col-sm-12">
                <h2>PROGETTIAMO E CONCRETIZZIAMO LA TUA CASA</h2>
            </div>
        </div>
        <a href="<?php echo $this->createUrl('/immobili') ?>" class="button fill">IMMOBILI IN VENDITA</a>
    </div>
    <div class="scroll"><span></span></div>
</section>
<!-- END SLIDER -->

<!-- PRESENTATION -->
<section id="presentation" class="section full-width dark">
    <div class="container">
        <div class="row">
            <!--            <div class="jt_col col-md-6">
                            <div class="carousel-wrap">
                                <div id="owl-studio" class="generic-carousel" data-animation-out="slideOutRight" data-animation-in="slideInLeft" data-dots="false">
                                    <div class="item">
                                        <img class="img-responsive" src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/home.jpg" alt="">
                                        <div class="slide-content"> 
                                            <div class="vertical-align">
                                                <h2 class="title light fz40">Soluzioni personalizzate</h2>
                                                <h3 class="subtitle light fz18">Personalizziamo tutte le tue idee per la costruzione o la ristrutturazione del tuo immobile.</h3>
                                                <a href="<?php echo $this->createUrl('/contatti') ?>" class="button">CONTATTACI</a>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="item">
                                        <img class="img-responsive" src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/soluzioni.jpg" alt="">
                                        <div class="slide-content"> 
                                            <div class="vertical-align">
                                                <h2 class="title light fz40">Soluzioni pronte</h2>
                                                <h3 class="subtitle light fz18">Abbiamo immobili nuovi già pronti e disponibili per la vendita, scopri le soluzioni migliori per te!</h3>
                                                <a href="<?php echo $this->createUrl('/immobili') ?>" class="button">SCOPRI</a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jt_col col-md-6 text-center align-table">
                            <div class="row align-table-cell">
                                <div class="jt_col col-md-8 jt_col col-md-offset-2">
                                    <div class="icon light fz30"><i class="icon-home"></i></div>
                                    <h2 class="title light fz40">partiamo da zero</h2>
                                    <h3 class="subtitle light fz18">Costruiamo immobili dalle fondamenta, seguendo rigorosamente una deontologia dedita alla creazione della tua casa dalle fondamenta al primo mattone.</h3>
                                </div>
                            </div>
                        </div>-->
        </div>
    </div>
</section>
<!-- END PRESENTATION -->

<?php $this->renderPartial('/site/_services') ?>

<!-- CERTIFICATIONS -->
<section id="certifications" class="section">
    <div class="container">
        <div class="row">
            <div class="jt_col col-md-8 jt_col col-md-offset-2 text-center">
                <h2 class="title main">CERTIFICAZIONI</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-3">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-clock-o"></i></div>-->
                    <h2 class="title fz20">OG1</h2>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-line-chart"></i></div>-->
                    <h2 class="title fz20">OG3</h2>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-desktop"></i></div>-->
                    <h2 class="title fz20">OG6</h2>
                </div>
            </div>
            <div class="col-sm-3">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-comments-o"></i></div>-->
                    <h2 class="title fz20">OG10</h2>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-line-chart"></i></div>-->
                    <h2 class="title fz20">OG11</h2>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-desktop"></i></div>-->
                    <h2 class="title fz20">OG24</h2>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="service text-center">
<!--                    <div class="icon fz32"><i class="icon fa fa-comments-o"></i></div>-->
                    <h2 class="title fz20">OS30</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 text-center voffset170">

            </div>
        </div>
    </div>
</section>
<!-- END CERTIFICATIONS -->


<?php //$this->renderPartial('/site/_portfolio') ?>

<?php $this->renderPartial('/site/_team') ?>

<?php
$m = ValoriDefault::model()->findByPk(1);
?>

<!-- COUNTERS -->
<section class="section nopadding" id="counters">
    <div class="container">
        <div class="row">
            <div class="jt_col col-sm-6 col-md-3">
                <div class="counter clearfix" data-count="<?php echo $m->field1 ?>">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/1.png" alt="fa-home"/>
                    <div class="data">
                        <span class="number">0</span>
                        <span class="literal">Appartamenti <br/>in vendita</span>
                    </div>
                </div>
            </div>
            <div class="jt_col col-sm-6 col-md-3">
                <div class="counter clearfix" data-count="<?php echo $m->field2 ?>">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/2.png" alt="fa-home"/>
                    <div class="data">
                        <span class="number">0</span>
                        <span class="literal">Appartamenti<br/> venduti</span>
                    </div>
                </div>
            </div>
            <div class="jt_col col-sm-6 col-md-3">
                <div class="counter clearfix" data-count="<?php echo $m->field3 ?>">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/3.png" alt="fa-home"/>
                    <div class="data">
                        <span class="number">0</span>
                        <span class="literal">Cantieri aperti</span>
                    </div>
                </div>
            </div>
            <div class="jt_col col-sm-6 col-md-3">
                <div class="counter clearfix" data-count="<?php echo $m->field4 ?>">
                    <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/4.png" alt="fa-home"/>
                    <div class="data">
                        <span class="number">0</span>
                        <span class="literal">Cantieri ultimati</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- END COUNTERS -->

<!-- OUR COMPANY -->
<section id="company" class="section">
    <div class="container">
        <div class="row voffset100">
            <div class="col-sm-10 col-sm-offset-1">
                <h2 class="title main">AZIENDA</h2>
                <div class="generic-carousel" data-animation-out="slideOutRight" data-animation-in="slideInLeft" data-dots="false">
                    <div class="item">
                        <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/azienda1.jpg" alt="" class="img-responsive">
                    </div>
                    <div class="item">
                        <img src="<?php echo Yii::app()->getBaseUrl(true) ?>/images/azienda2.jpg" alt="" class="img-responsive">
                    </div>
                </div>
                <h2 class="post title">DAL 1994 AL TUO SERVIZIO</h2>
                <div class="text-content">
                    <p>L'impresa opera nel settore delle costruzioni edili, civili, industriali e delle opere pubbliche.</p>
                    <p>In questi anni l'attività dell'Azienda ha mantenuto lo stesso entusiasmo per il proprio lavoro cercando di seguire l'evoluzione dei tempi legati al settore immobiliare e delle costruzioni in genere.</p>
                    <p><strong>La nostra azienda si occupa direttamente della progettazione, costruzione e commercializzazione degli immobili, fornendo un servizio a 360° e garantendo così un notevole risparmio in termini di costi per i clienti.</strong></p>
                    <p>L'impresa, la cui sede è situata in Agropoli in provincia di Salerno, opera su tutto il territorio con grande competenza e professionalità. La qualità delle strutture realizzate e delle tecniche utilizzate in cantiere hanno permesso di ideare e conseguire progetti con uno standard di qualità sempre maggiore. Basandosi proprio su questi requisiti l'impresa è riuscita a raggiungere obiettivi fondamentali come la soddisfazione di ogni cliente.</p>
                    <p>L'impresa edile è costantemente affiancata da uno <strong>studio tecnico</strong> composto da tecnici professionisti di comprovata esperienza. Nel corso degli anni insieme all'impresa si è dunque valorizzato un team di professionisti che si occupa personalmente di tutte le fasi necessarie che vanno dalla progettazione preliminare a quella esecutiva, passando per la direzione lavori, il coordinamento della sicurezza, la progettazione strutturale e il collaudo.</p>
                    <p>Naviga il sito per leggere le schede di dettaglio degli immobili in vendita o in affitto oppure contattaci direttamente per richiedere informazioni e/o consulenze tecniche.</p>

                </div>
            </div>
        </div>
    </div>
</section>
<!-- END OUR COMPANY -->

<!-- CONTACT -->
<section class="section" id="contact">
    <div class="container">
        <div class="row">
            <div class="jt_col-col-md-12 text-center voffset100">
                <h3 class="title main voffset100">CONTATTI</h3>
                <h3 class="title fz20 voffset0">VUOI UNA CONSULENZA?</h3>
                <h3 class="title primary fz50">+39 0974 824945</h3>
            </div>
            <div class="jt_col-col-md-12 voffset100">
                <form id="contactform" action="<?php echo $this->createUrl('/site/mail') ?>" method="post">
                    <div class="row text-center contact-form">
                        <div class="jt_col col-md-4">
                            <input id="name" name="name" type="text" class="required form-control" placeholder="Nome">
                        </div>
                        <div class="jt_col col-md-4">
                            <input id="email" name="email" type="text" class="required form-control" placeholder="Email">
                        </div>
                        <div class="jt_col col-md-4">
                            <input id="phone" name="phone" type="text" class="form-control" placeholder="Telefono">
                        </div>
                        <div class="jt_col col-md-12">
                            <textarea id="message" name="message" class="required form-control" placeholder="Messaggio"></textarea>
                        </div>
                        <div class="jt_col col-md-4 col-md-offset-4"><button type="submit" class="button fill">INVIA</button></div>
                        <div class="jt_col col-md-4 col-md-offset-4">
                            <div class="formSent success"><strong>Messaggio inviato con successo.</strong> Grazie per averci contattato!</div>
                        </div>
                    </div>
                </form>
            </div>
            <div class="jt_col-col-md-12 voffset100 text-center">
                <h4 class="title fz16">ING. ANGELO ERRICO</h4>
                <h4 class="title fz16">via Difesa 6, Agropoli (SA)</h4>
                <h4 class="title fz16">TEL\FAX 0974 824945 | P.IVA 48789562</h4>
                <h4 class="title fz16 primary voffset60">APPALTITEMAIMPIANTI@LIBERO.IT</h4>
            </div>
        </div>
    </div>
</section>
<style type="text/css">
    .owl-dots{
        display: none !important;
    }
</style>